### ISSUE TITLE
Installing through npm is not working

### ISSUE THREAD

**Issue by bensampaio** [mdreizin/webpack-config-stream#18]
My project has a dependency on `gulp-webpack-build` version ^0.12.1. Each time I try to run `npm install` I get the following error: "'webpack-config' is not in the npm registry. It was specified as a dependency of 'gulp-webpack-build'.". When I searched for `webpack-config` in the npm registry I found out that it seems to no longer exist...

I also tried to use `webpack-config-stream` instead of `gulp-webpack-build` but that didn't solve the problem. Any ideas? I need an urgent solution for this, we need to deploy in production today and we are dependent on this problem...

**Comment by eudisd** [comment]
+1

**Comment by deepoke** [comment]
+1

**Comment by mdreizin** [comment]
@bensampaio @eudisd @deepoke I'm really sorry for inconvenience. I have accidentally run command `npm publish .` instead of` npm unpublish`. I have already contacted npm support about that and I'm waiting for the response.

Also I have already opened an issue https://github.com/mdreizin/webpack-config/issues/8.

**Comment by mdreizin** [comment]
Unfortunately I can't republish all missing version due to npm limitations:

```
You cannot publish over the previously published version 0.8.0. Try bumping the version to 2.0.0".
```

I have significantly improved https://github.com/mdreizin/webpack-config and https://github.com/mdreizin/webpack-config-stream and also added https://github.com/semantic-release/semantic-release to reduce manual effort.

I can publish new version to resolve this issue, but you need to do some migrations and migration documentation is not ready yet.

**Comment by nathanpeck** [comment]
Can't you republish the old version at 0.8.1 or something like that?

**Comment by mdreizin** [comment]
Sorry for inconvenience. I have published it as `0.8.1` and now all packages should work now.

**Comment by nathanpeck** [comment]
![giphy-1](https://cloud.githubusercontent.com/assets/3495674/10586547/b341332e-766a-11e5-8fab-ffdd96e7e2c9.gif)

**Comment by pablolmiranda** [comment]
All packages with dependency on versions before 0.8.1 are broken. All the versions are gone, except 0.8.1.

**Comment by bensampaio** [comment]
It works! Thank you ;)
